=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/specification-configuration-1.0.dtd
<!-- Specification file-based configuration document.

<!DOCTYPE specification-configuration SYSTEM "specification-configuration-1.0.dtd">

An instance of this document contains property settings and references
to specification definition files for a Specification Context instance to be loaded 
on a spring startup listener.
-->

<!-- element  hierarchy definition-->
<!ELEMENT specification-instance (request,response)>

<!ELEMENT request (head,content)>

<!ELEMENT response (content)>
<!ELEMENT head (request-type,version)>
<!ELEMENT request-type (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT content (property-field|complex-field|list-field)+>

<!-- field type definition:field,complex-field-->

<!-- field-->
<!ELEMENT property-field ANY>
<!ATTLIST property-field id CDATA #REQUIRED>
<!ATTLIST property-field name CDATA #REQUIRED>
<!ATTLIST property-field length CDATA  #IMPLIED>
<!ATTLIST property-field nullable (false|true) "false">
<!ATTLIST property-field type (a|n|s|ans|an|date|timestamp|money|o|c) "ans"> 
<!ATTLIST property-field optional (false|true) "false" >
<!ATTLIST property-field depend-field IDREFS #IMPLIED>
<!ATTLIST property-field depend-value CDATA #IMPLIED>

<!--complex-field-->
<!ELEMENT complex-field (property-field)+>
<!ATTLIST complex-field id ID #REQUIRED>
<!ATTLIST complex-field name CDATA #REQUIRED> 
<!ATTLIST complex-field nullable (false|true) "false"> 
<!ATTLIST complex-field typeClass CDATA #REQUIRED> 
<!ATTLIST complex-field optional (false|true) "false" >
<!ATTLIST complex-field depend-field IDREFS #IMPLIED>
<!ATTLIST complex-field depend-value CDATA #IMPLIED> 


<!--list-field -->
<!ELEMENT list-field (ref)> 
<!ATTLIST list-field id ID #REQUIRED>
<!ATTLIST list-field name CDATA #REQUIRED> 
<!ATTLIST list-field nullable (false|true) "false">  
<!ATTLIST list-field optional (false|true) "false" >
<!ATTLIST list-field depend-field IDREFS #IMPLIED>
<!ATTLIST list-field depend-value CDATA #IMPLIED> 

<!--list:ref -->
<!ELEMENT ref EMPTY> 
<!ATTLIST ref value IDREFS #REQUIRED>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/open_merchant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SME101</request-type>
			<version>1.0</version>
		</head>
		<content>
		<!-- 二级商户同步 -->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="entranceMemId" type="an" name="entranceMemId" nullable="false" length="32"/>
			<property-field id="email" type="ans" name="email" nullable="false" length="32"/>
			<property-field id="name" type="ans" name="name" nullable="false" length="64"/>
			<property-field id="alias" type="ans" name="alias" nullable="false" length="40"/>
			<property-field id="province" type="n" name="province" nullable="false" length="10" />
			<property-field id="city" type="n" name="city" nullable="false" length="10" />
			<property-field id="county" type="n" name="county" nullable="false" length="10"/>
			<property-field id="taxregNo" type="an" name="taxregNo" nullable="false" length="32"/>
			<property-field id="licenceNo" type="an" name="licenceNo" nullable="false" length="32"/>
			<property-field id="orgCode" type="an" name="orgCode" nullable="false" length="10"/>
			<property-field id="address" type="ans" name="address" nullable="false" length="256"/>
			<property-field id="postCode" type="n" name="postCode" nullable="false" length="6"/>
			<property-field id="primaryBusiness" type="n" name="primaryBusiness" nullable="false" length="1"/>
			<property-field id="corporation" type="ans" name="corporation" nullable="false" length="32"/>
			<property-field id="corpCertType" type="n" name="corpCertType" nullable="false" length="1"/>
			
			<property-field id="corpCertNo" type="ans" name="corpCertNo" nullable="false" length="32"/>
			<property-field id="despositBank" type="n" name="despositBank" nullable="false" length="12"/>
			
			<property-field id="accountName" type="ans" name="accountName" nullable="false" length="64"/>
			<property-field id="accountNo" type="an" name="accountNo" nullable="false" length="32"/>
			<property-field id="contacts" type="ans" name="contacts" nullable="true" length="32"/>
			<property-field id="contactsTelNo" type="ans" name="contactsTelNo" nullable="false" length="16"/>
			<property-field id="contactsAddr" type="ans" name="contactsAddr" nullable="true" length="128"/>
			<property-field id="contactsPostCode" type="an" name="contactsPostCode" nullable="true" length="6" />
			<property-field id="contactsEmail" type="ans" name="contactsEmail" nullable="true" length="64" />
			<property-field id="mac" type="ans" name="mac" nullable="false" length="256"/>
			
		</content>
	</request>
	<response>
		<content>
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="rescode" type="an" name="rescode" nullable="false" length="2"/>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" length="128"/>
			<property-field id="minorMerchNo" type="an" name="minorMerchNo" nullable="false" length="15"/>
			<property-field id="mac" type="ans" name="mac" nullable="false" length="256"/>

		</content>
	</response>
</specification-instance>
