=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/specification-configuration-1.0.dtd
<!-- Specification file-based configuration document.

<!DOCTYPE specification-configuration SYSTEM "specification-configuration-1.0.dtd">

An instance of this document contains property settings and references
to specification definition files for a Specification Context instance to be loaded 
on a spring startup listener.
-->

<!-- element  hierarchy definition-->
<!ELEMENT specification-instance (request,response)>

<!ELEMENT request (head,content)>

<!ELEMENT response (content)>
<!ELEMENT head (request-type,version)>
<!ELEMENT request-type (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT content (property-field|complex-field|list-field)+>

<!-- field type definition:field,complex-field-->

<!-- field-->
<!ELEMENT property-field ANY>
<!ATTLIST property-field id CDATA #REQUIRED>
<!ATTLIST property-field name CDATA #REQUIRED>
<!ATTLIST property-field length CDATA  #IMPLIED>
<!ATTLIST property-field nullable (false|true) "false">
<!ATTLIST property-field type (a|n|s|ans|an|date|timestamp|money|o|c) "ans"> 
<!ATTLIST property-field optional (false|true) "false" >
<!ATTLIST property-field depend-field IDREFS #IMPLIED>
<!ATTLIST property-field depend-value CDATA #IMPLIED>

<!--complex-field-->
<!ELEMENT complex-field (property-field)+>
<!ATTLIST complex-field id ID #REQUIRED>
<!ATTLIST complex-field name CDATA #REQUIRED> 
<!ATTLIST complex-field nullable (false|true) "false"> 
<!ATTLIST complex-field typeClass CDATA #REQUIRED> 
<!ATTLIST complex-field optional (false|true) "false" >
<!ATTLIST complex-field depend-field IDREFS #IMPLIED>
<!ATTLIST complex-field depend-value CDATA #IMPLIED> 


<!--list-field -->
<!ELEMENT list-field (ref)> 
<!ATTLIST list-field id ID #REQUIRED>
<!ATTLIST list-field name CDATA #REQUIRED> 
<!ATTLIST list-field nullable (false|true) "false">  
<!ATTLIST list-field optional (false|true) "false" >
<!ATTLIST list-field depend-field IDREFS #IMPLIED>
<!ATTLIST list-field depend-value CDATA #IMPLIED> 

<!--list:ref -->
<!ELEMENT ref EMPTY> 
<!ATTLIST ref value IDREFS #REQUIRED>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/sign.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SMA101</request-type>
			<version>1.0</version>
		</head>
		<content>
		<!--签到 -->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"></property-field>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"></property-field>
			<property-field id="notifyUrl" type="ans" name="notifyUrl" nullable="false"  length="256"></property-field>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"></property-field>			
		</content>
	</request>
	<response>
		<content>			
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"  length="15"></property-field>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false"  length="16"></property-field>
			<property-field id="rescode" type="an" name="rescode" nullable="false"  length="2"></property-field>
			<property-field id="resdes" type="an" name="resdes" nullable="false" optional="true"  length="128"></property-field>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"></property-field>
		</content>
	</response>
</specification-instance>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/sycindividualquery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SIN102</request-type>
			<version>1.0</version>
		</head>
		<content>
		<!-- 个人会员同步查询 -->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="memberId" type="an" name="memberId" nullable="true"  length="15" optional="true"/>
			<property-field id="entranceMemId" type="an" name="entranceMemId" nullable="false"  length="32"/>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"/>
		</content>
	</request>
	<response>
		<content>
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="rescode" type="an" name="rescode" nullable="false" length="2"/>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" length="128"/>
			<property-field id="memberId" type="an" name="memberId" nullable="false"  length="15"/>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"/>
		</content>
	</response>
</specification-instance>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/open_person.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SIN101</request-type>
			<version>1.0</version>
		</head>
		<content>
	<!-- 	个人会员同步 -->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="entranceMemId" type="an" name="entranceMemId" nullable="false" length="32"/>
			<property-field id="phone" type="n" name="phone" nullable="false" length="11"/>
			<property-field id="email" type="ans" name="email" nullable="true" length="32" optional="true"/>
			<property-field id="name" type="ans" name="name" nullable="false" length="32"/>
			<property-field id="loginName" type="ans" name="loginName" nullable="false" length="32"/>
			<property-field id="loginPwd" type="ans" name="loginPwd" nullable="false" length="256"/>
			<property-field id="gender" type="a" name="gender" nullable="false"  length="1"/>
			<property-field id="mac" type="ans" name="mac" nullable="false" length="256"/>
		</content>
	</request>
	<response>
		<content>
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="rescode" type="an" name="rescode" nullable="false" length="2"/>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" length="128"/>
			<property-field id="memberId" type="an" name="merchId" nullable="false" length="15"/>
		    <property-field id="mac" type="ans" name="mac" nullable="false"  length="256"/>
		</content>
	</response>
</specification-instance>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/sycmerchquery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SME102</request-type>
			<version>1.0</version>
		</head>
		<content>
	<!-- 	商户同步查询 -->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="minorMerchNo" type="an" name="minorMerchNo" nullable="true" length="15" optional="true"></property-field>
			<property-field id="entranceMemId" type="an" name="entranceMemId" nullable="false"  length="32"/>
			<property-field id="mac" type="ans" name="mac" nullable="false" length="256"></property-field>			
		</content>
	</request>
	<response>
		<content>			
			<property-field id="merchNo" type="an" name="merchNo" nullable="false" length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="rescode" type="an" name="rescode" nullable="false"  length="2"></property-field>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" optional="true"  length="128"></property-field>
			<property-field id="minorMerchNo" type="an" name="minorMerchNo" nullable="false" length="15"></property-field>
			<property-field id="status" type="an" name="status" nullable="false"  length="2"></property-field>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"></property-field>
		</content>
	</response>
</specification-instance>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/query_member_account.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SAC101</request-type>
			<version>1.0</version>
		</head>
		<content>
		<!--会员账户查询 -->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"  length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false"  length="16"/>
			<property-field id="memberType" type="an" name="memberType" nullable="false"  length="2"/>
		    <property-field id="memberId" type="an" name="memberId" nullable="false" length="15" />
		
			<property-field id="mac" type="ans" name="mac" nullable="false" />
		</content>
	</request>
	<response>
		<content>
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"  length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false"  length="16"/>
			<property-field id="rescode" type="an" name="rescode" nullable="false" length="2"/>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" length="128"/>
			<property-field id="mac" type="ans" name="mac" nullable="false" />
			<list-field id="acounts" name="accounts">
				<ref value="account"></ref>
			</list-field>
			<complex-field id="account" name="account"
				typeClass="com.zlebank.zplatform.specification.message.content.Account">
				<property-field name="acctCode" id="acctCode" type="an"  length="32"/>
				<property-field name="acctName" id="acctName" type="ans"  length="256"/>
				<property-field name="balance" id="balance" type="money"  length="12"/>
				<property-field name="frozenBalance" id="frozenBalance" type="money" length="12"/>
				<property-field name="totalBalance" id="totalBalance" type="money" length="12"/>
				<property-field name="currency" id="currency" type="an"  length="3" />
				<property-field name="usage" id="usage" type="an"  length="128"/>
				<property-field name="status" id="status" type="an"  length="128"/>
			</complex-field> 
		</content>
	</response>
</specification-instance>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/query_bank_no.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SPA101</request-type>
			<version>1.0</version>
		</head>
		<content>
		<!-- 账户收支明细查询-->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"  length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false"  length="16"/>
			<property-field id="bankName" type="ans" name="bankName" nullable="false" length="128"/>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"/>
			
		</content>
	</request>
	<response>
		<content>
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"  length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false" length="16"/>
			<property-field id="rescode" type="an" name="rescode" nullable="false" length="2"/>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" length="128"/>
			<list-field id="bankInfos" name="bankInfos">
				<ref value="bankInfo"></ref>
			</list-field>
			<complex-field id="bankInfo" name="bankInfo"
				typeClass="com.zlebank.zplatform.specification.message.content.BankInfo">
				<property-field name="bankNode" id="bankNode" type="an" length="12"/>
				<property-field name="acctName" id="acctName" type="an" length="12"/>
				<property-field name="bankName" id="bankName" type="ans" length="64"/>
				<property-field name="bankAdress" id="bankAdress" type="ans" length="64"/>
			</complex-field>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"/>

		</content>
	</response>
</specification-instance>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/sycindividualnotify.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>AIN103</request-type>
			<version>1.0</version>
		</head>
		<content>
		<!-- 个人会员同步通知 -->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"></property-field>
			<property-field id="srcSessionId" type="an" name="srcSessionId" nullable="false"></property-field>
			<property-field id="memberId" type="an" name="memberId" nullable="false"></property-field>
			<property-field id="status" type="an" name="status" nullable="false"></property-field>		
			<property-field id="mac" type="ans" name="mac" nullable="false"></property-field>		
		</content>
	</request>
	<response>
		<content>			
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"></property-field>
			<property-field id="srcSessionId" type="an" name="sessionId" nullable="false"></property-field>
			<property-field id="rescode" type="an" name="rescode" nullable="false"></property-field>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" optional="true" ></property-field>
			<property-field id="mac" type="ans" name="mac" nullable="false"></property-field>
		</content>
	</response>
</specification-instance>

=== cactus-law/zplatform-infrastructure/zplatform-specification/src/main/resources/specification/query_trade_detail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification-instance SYSTEM "specification-configuration-1.0.dtd">
<specification-instance>
	<request>
		<head>
			<request-type>SAC103</request-type>
			<version>1.0</version>
		</head>
		<content>
		<!-- 账户收支明细查询-->
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"  length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false"  length="16"/>
			<property-field id="acctCode" type="an" name="acctCode" nullable="false" length="32"/>
			<property-field id="from" type="ans" name="from" nullable="false" length="10"/>
			<property-field id="to" type="ans" name="to" nullable="false" length="10"/>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"/>
			
		</content>
	</request>
	<response>
		<content>
			<property-field id="merchNo" type="an" name="merchNo" nullable="false"  length="15"/>
			<property-field id="sessionId" type="an" name="sessionId" nullable="false"  length="16"/>
			<property-field id="rescode" type="an" name="rescode" nullable="false" length="2"/>
			<property-field id="resdes" type="ans" name="resdes" nullable="false" length="128"/>
			<list-field id="entryDetails" name="entryDetails">
				<ref value="entryDetail"></ref>
			</list-field>
			<complex-field id="entryDetail" name="entryDetail"
				typeClass="com.zlebank.zplatform.specification.message.content.EntryDetail">
				<property-field name="seqNo" id="seqNo" type="an" length="16"/>
				<property-field name="acctCode" id="acctCode" type="an" length="32"/>
				<property-field name="flag" id="flag" type="a" length="1"/>
				<property-field name="amount" id="amount" type="ans" length="12"/>
				<property-field name="currency" id="currency" type="an" length="3"/>
			</complex-field>
			<property-field id="mac" type="ans" name="mac" nullable="false"  length="256"/>

		</content>
	</response>
</specification-instance>
